name: alelo_clone_ui_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg:
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
  fonts:
    - family: Museosans
      fonts:
        - asset: assets/fonts/museo_sans_300.ttf
        - asset: assets/fonts/museo_sans_500.ttf
        - weight: 500
        - asset: assets/fonts/museo_sans_100.ttf
        - weight: 100
        - asset: assets/fonts/museo_sans_700.ttf
        - weight: 700